name: 'Update Web Resource in Dynamics'
description: 'Use this action to update a web resource in your dynamics 365 CRM instance'
branding:
  icon: 'arrow-up-right'
  color: 'blue'
inputs:
    dynamics-url:
        description: 'The URL of your Microsoft Dynamics instance'
        required: true
    application-id:
        description: 'The Application ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    application-secret:
        description: 'The Application Secret of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    tenant-id:
      description: 'The Tenant ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
      required: true
    web-resource-data-to-update:
      description: 'A | seperated list of the web resource data to update. You provide the guid and the filepath seperated by a comma. So 000-000-000-000,path/to/file.js|000-000-000-001,path/to/file.css'
      required: true
runs:
  using: "composite"
  steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: composer install -d ${{ github.action_path }}/src/ -o
      shell: bash

    - name: Publish all changes
      shell: bash
      env:
        INSTANCE_URL: ${{ inputs.dynamics-url }}
        APPLICATION_ID: ${{ inputs.application-id }}
        APPLICATION_SECRET: ${{ inputs.application-secret }}
        TENANT_ID: ${{ inputs.tenant-id }}
      run: php ${{ github.action_path }}/src/index.php "${{ inputs.web-resource-data-to-update }}"
